### ISSUE TITLE
Sepia Home

### ISSUE THREAD

**Issue by gbossley** [SEPIA-Framework/sepia-installation-and-setup#18]
Hi,
This is exciting, but I have nearly no idea what I'm doing. I've tried to execute your instructions, and choose 4 after running run-sepia.bat.

I get this error:
"Windows cannot find "elasticsearch.bat'. Make sure you typed the name correctly and then try again."

**Comment by gbossley** [comment]
Resolved at the command line by changing to the appropriate drive and directory but I now have another error:
Enter a number plz (0 to exit): 4

Starting Elasticsearch, please wait ...
.
...................
....FAIL

**Comment by fquirin** [comment]
Hi @gbossley , issues in this repository are usually reserved for bugs in the installation package etc.. If you need help with the installation I recommend the "new" discussions section: https://github.com/SEPIA-Framework/sepia-docs/discussions

Looking at your error message alone its hard to say what went wrong. A wild guess: Java isn't installed properly. Your initial problem is kind of weird though since on Windows you can simply double-click setup.bat and the folder doesn't really matter :thinking: 

I will close this issue for now. Feel free to ask your question again in the discussions section mentioned above.
